### ISSUE TITLE
Hard cap

### ISSUE THREAD

**Issue by kingcocomango** [district0x/contribution#1]
The hard cap limits the next transaction and not the current one, and it's unlikely the last transaction will set the contributions to exactly equal the hard cap.

 In a similar vein, in the unlikely situation a tx breaks both the hard and soft cap simultaneously , the hard cap will be completely ignored from that point forward.

These don't deserve an issue by themselves so they're here, typo @171 cao-> cap & @292 tokens

**Comment by madvas** [comment]
Thank you for pointing this out! I've pushed fix
