### ISSUE TITLE
Possible issue in Ownable.sol

### ISSUE THREAD

**Issue by adamdossa** [district0x/contribution#6]
Hey District0x guys,

There is a comment in Ownable.sol:
```
/// @param _newOwner The address of the new owner. 0x0 can be used to create
///  an unowned neutral vault, however that cannot be undone
```

However, if you call `changeOwner(0x0)`, this will set `newOwner` to 0x0, but in order for `owner` to be then be set to `newOwner`, address 0x0 would need to call `acceptOwnership` which I don't think is possible.

So - I think either the comment is wrong, or the contract needs to be implemented differently. Probably worth clarifying either way.

Thanks,
Adam

**Comment by madvas** [comment]
Good point, I overlooked this. Thanks Adam!

**Comment by GriffGreen** [comment]
Yeah! Great catch @adamdossa I guess to make a neutral vault you would need to make a custom contract that can accept ownership and do basically nothing else.
