### ISSUE TITLE
DNT tokens locked in the Contribution contract

### ISSUE THREAD

**Issue by jakub-wojciechowski** [district0x/contribution#7]
Hi, @madvas!

This is a really cool project. I'm impressed by all of you achieved so far and looking forward to seeing how it evolves in the future.

There is one issue that I've discovered reading your code.
From all of the tokens that are generated in:

`function setDistrict0xNetworkToken(address _district0xNetworkToken)`

the amount `CONTRIB_PERIOD1_STAKE` is left in possession of `District0xContribution`.

After the sale period is ended `require(endTime < now)` there is an attempt to distribute all of the `CONTRIB_PERIOD1_STAKE` among contributors in:

`function compensateContributors(uint offset, uint limit) `

Despite this attempt, there may be some tokens left on the `District0xContribution` contract in any the two cases:

* exception in district0xNetworkToken.transfer(contributorAddress, contributors[contributorAddress].amountCompensated);
* tokens are sent to `District0xContribution` by mistake, which is always enabled:

```
function onTransfer(address _from, address _to, uint _amount) public returns (bool) {
  return tokenTransfersEnabled || _from == address(this) || _to == address(this);
}
```

There is no mechanism to reclaim theses tokens as DNT is permanently blocked for reclaim in: 

```
function reclaimToken(address tokenAddr) external onlyOwner {
    require(!isTokenSaleToken(tokenAddr));
    ERC20Basic tokenInst = ERC20Basic(tokenAddr);
    uint256 balance = tokenInst.balanceOf(this);
    tokenInst.transfer(msg.sender, balance);
  }
```

**This results in some of the DNT tokens may be stuck in this contract forever.** 

One of the solutions is to enable reclaim mechanism after the contribution period is over. Happy to send PR if you want.

Please let me know what do you think about it?

**Comment by jbaylina** [comment]
The first point you mention is about what happens if the transfer fails.  I don’t see any way that it can fail as this method doesn’t call any untrusted code.

About the second point, the tokens stacked in the contribution contract, this is required so that the owners cannot trick the distribution. (They might send the tokens with a different distribution).

In general, is’s more frequent that users  send the tokens to the token contract. This case is protected in the code.

Also the responsibility of where the user sends their tokens is theirs alone, while it would be nice to protect them from making mistakes, we cannot protect them from all of the mistakes all of the time.

That said, the only thing that may be added, is a protection enabled only when `compensatedCount == contributorsCount`

**Comment by jakub-wojciechowski** [comment]
Hi @jbaylina, it's always a pleasure to read your response :)

The first point, yes obviously your are right. I was fooled by a google when I quickly searched for Minime ERC223 compatibility and [PR](https://github.com/Giveth/minime/pull/11/files) popped up but apparently, it's not merged yet.
 
For the second one, I agree that there is no moral obligation to protect users from making silly mistakes. But the improvement isn't expensive as the District0xContribution already implements HasNoTokens.

BTW, having compensated counter would be a nice improvement as the state change is not reversible it's easy to implement and may greatly simplify function getUncompensatedContributors function and there will be no need for offsetting. 

If you decide to implement this improvement please be aware of the case when compensatedCount == contributorsCount == 0 at the beginning of the crowdsale (you may check for `require(endTime < now)`).

**Comment by jbaylina** [comment]
@jakub-wojciechowski
This might be a good addition to the contract, but in practice, it is best to keep the code frozen as long as possible before deployment and only change it for critical issues, small improvements at the last minute could introduce critical bugs that would have been caught with a community review.

**Comment by madvas** [comment]
Yes. Thanks Jakub for those suggestions. These are nice-to-have improvements, but not really necessary. At the point, I'm not gonna do any changes to code unless totally necessary.
